sample array using numpy


In [12]:
import numpy as np

odd = [1,3,5,7,9]
even = [2,4,6,8,10]
odd_array = np.array(odd)
even_array = np.array(even)
print(odd_array)
print(even_array)
print(odd_array.shape)
print(odd_array.size)


[1 3 5 7 9]
[ 2  4  6  8 10]
(5,)
5


compact numpy array : Finding the squares from 1 to 10

In [6]:
squares = np.array([i * i for i in range(1,11)])
print(squares)

[  1   4   9  16  25  36  49  64  81 100]


Ways to create array:


In [9]:
from numpy import zeros
from numpy import ones
from numpy import random

array1 = zeros([3,4])
print(array1)
array2 = ones([50])
print(array2)
array3 = np.random.random(size = (3,2))
print(array3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]
[[0.595908   0.13959596]
 [0.99932092 0.3319417 ]
 [0.08196766 0.95705841]]


RESHAPING OF ARRAY:(modifying number of rows and columns)

In [13]:
quant = np.array([(8,9,10),(11,12,13)])

print("The original array:\n", quant)


quantity = quant.reshape(3,2)
print(quantity)

The original array:
 [[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


INDEXING AND SLICING:


In [17]:
print(odd_array[2])
print(quantity[0][1])

print(quantity[1:,0:1])

5
9
[[10]
 [12]]


OPERATIONS ON 1 D ARRAY:


In [20]:
array1 = np.array([120,230,310,410,150])
print('array1: ',array1,' length of array1 is ',len(array1))

array2 = np.arange(5);
print('array2: ',array2,' length of the array2 is ',len(array2))

array1:  [120 230 310 410 150]  length of array1 is  5
array2:  [0 1 2 3 4]  length of the array2 is  5


ADDING TWO ARRAYS:

In [22]:
sum = array1 + array2
print(sum)


[120 231 312 413 154]


Numpy arrays with comoparison expressions:


In [24]:
numbers = np.array([range(1,11)])
even = numbers%2 == 0
print('even numbers are ',even)
numbers[even]

even numbers are  [[False  True False  True False  True False  True False  True]]


array([ 2,  4,  6,  8, 10])

OPERATIONS ON 2D ARRAY:

In [31]:
array_1 = np.array([[56,23,87],[45,37,29]])
array_2 = np.array([[45,83,27],[37,27,84]])
print(array_1)
print(array_2)
res_array_1 = 2*array_1
res_array_2 = 3+ array_2 
print(res_array_1)
print(res_array_2)

res_sum = res_array_1 + res_array_2
print(res_sum)


print('multiplication of resultant arrays :',res_array_1 * res_array_2)

[[56 23 87]
 [45 37 29]]
[[45 83 27]
 [37 27 84]]
[[112  46 174]
 [ 90  74  58]]
[[48 86 30]
 [40 30 87]]
[[160 132 204]
 [130 104 145]]
multiplication of resultant arrays : [[5376 3956 5220]
 [3600 2220 5046]]


MATRIX MUKLTIPLIACTION AND DOT PRODUCT

In [41]:
array1 = np.array([[8,9],[28,17]])
array2 = np.array([[29,10],[28,17]])
print(array1)
print(array2)

print('The matrix multiplication of two rfesultant array is ',array1 @ array2)

[[ 8  9]
 [28 17]]
[[29 10]
 [28 17]]
The matrix multiplication of two rfesultant array is  [[ 484  233]
 [1288  569]]


ARITHMETIC FUNCTIONS ON ARRAY:

In [45]:
price =  np.array([5,7,8,2,4])
summed_price = np.sum(price)
print('sum: ',summed_price)

print('minimum_price',np.min(price))

print('powered :',np.power(price,3))


sum:  26
minimum_price 2
powered : [125 343 512   8  64]


CONCATENATION OF 1D AND 2D ARRAYS:

In [49]:
odd = np.array(range(1,10,2))
even = np.array(range(2,11,2))
numbers = np.concatenate([odd,even])
print(numbers)

[ 1  3  5  7  9  2  4  6  8 10]


STACKING OF ARRAYS:

In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])

print('...stacking....')

res = np.stack((a1,a2),axis =1)
print(res)

print('......hstack....')
res = np.hstack((a1,a2))
print(res)

print('......dstack......')

res = np.dstack((a1,a2))
print(res)

print('.....vstack.....')
res = np.vstack((a1,a2))
print(res)


print('2D MATRIX USING BLOCKS')


m1 = np.array([4])
m2 = np.array([5])
m3 = np.array([6])
m4 = np.array([7])

array = np.array([[m1,m2],[m3,m4]])

print(array)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[[ 1  7]
  [ 2  8]
  [ 3  9]]

 [[ 4 10]
  [ 5 11]
  [ 6 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2D MATRIX USING BLOCKS
[[[4]
  [5]]

 [[6]
  [7]]]


SPLITTING OF ARRAY:


In [78]:
array1 = np.arange(10)
print(np.split(array1, 2))
print(np.split(array1,[6,7]))


print('......RESHAPING......')


array2  = array1.reshape(2,5)

print('....reshaped array...')
print(array2)
print('....splitting array into row wise..')

print(np.vsplit(array2,2))






[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
[array([0, 1, 2, 3, 4, 5]), array([6]), array([7, 8, 9])]
......RESHAPING......
....reshaped array...
[[0 1 2 3 4]
 [5 6 7 8 9]]
....splitting array into row wise..
[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
